version: "2"
services:
  hockeypool:
    container_name: hockeypool
    restart: always
    build: .
    ports:
      - 3030
      - 80
      - 9229
    links:
      - hockeypool-mongodb
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "."
  hockeypool-mongodb:
    container_name: hockeypool-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017