version: "2"
services:
  hockeypool:
    container_name: hockeypool
    restart: always
    build: .
    ports:
      - 3030
      - 80
      - 9229
    links:
      - hockeypool-mongodb
    command: "npm start"
  hockeypool-mongodb:
    container_name: hockeypool-mongodb
    image: mongo
    ports:
      - 27017