version: "2"
services:
  hockeypool:
    container_name: hockeypool
    restart: always
    image: jbiffis/hockeypool:latest
    ports:
      - 3030
      - 80
    links:
      - hockeypool-mongodb
  hockeypool-mongodb:
    container_name: hockeypool-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017